# Generated by Django 4.1.7 on 2023-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('hd', models.CharField(max_length=200)),
                ('pr', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200, null='True')),
            ],
        ),
    ]
