# Generated by Django 4.1.7 on 2023-05-28 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tag',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='hd',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='pr',
            new_name='model',
        ),
        migrations.AddField(
            model_name='card',
            name='info',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
