# Generated by Django 4.1.7 on 2023-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_tag_card_brand_rename_hd_card_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
