# Generated by Django 4.1.7 on 2023-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_card_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='info',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
