# Generated by Django 4.1.7 on 2023-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_details_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='title',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='details',
            field=models.TextField(max_length=200),
        ),
    ]
