# Generated by Django 4.1.7 on 2023-06-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cart_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_model',
            old_name='price',
            new_name='prices',
        ),
    ]
