# Generated by Django 4.1.7 on 2023-06-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_price_cart_model_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_model',
            old_name='img',
            new_name='imgs',
        ),
    ]
