# Generated by Django 4.1.7 on 2023-06-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_img_cart_model_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_model',
            old_name='model',
            new_name='modls',
        ),
    ]
