# Generated by Django 4.1.7 on 2023-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_model_cart_model_modls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_model',
            old_name='modls',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cart_model',
            old_name='imgs',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='cart_model',
            old_name='title',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='cart_model',
            old_name='prices',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cart_model',
            name='brand',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='cart_model',
            name='info',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
