# Generated by Django 4.1.7 on 2023-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_modls_cart_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='model',
            field=models.CharField(max_length=200, null='True'),
        ),
        migrations.AlterField(
            model_name='cart_model',
            name='model',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
